SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `qwins_answer`;
CREATE TABLE IF NOT EXISTS `qwins_answer` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` int(10) UNSIGNED NOT NULL,
  `content` varchar(150) NOT NULL,
  `correct` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 - wrong;1 - correct',
  PRIMARY KEY (`id`),
  KEY `question_FK` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `qwins_category`;
CREATE TABLE IF NOT EXISTS `qwins_category` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(125) NOT NULL,
  `difficulty` tinyint(3) UNSIGNED NOT NULL DEFAULT '0',
  `language` int(11) NOT NULL DEFAULT '0' COMMENT '0 – polish;1 – english',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `qwins_question`;
CREATE TABLE IF NOT EXISTS `qwins_question` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` int(10) UNSIGNED NOT NULL,
  `content` varchar(150) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `category_FK` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `qwins_answer`
  ADD CONSTRAINT `question_FK` FOREIGN KEY (`question_id`) REFERENCES `qwins_question` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
